---
type: object
properties:
  logging:
    type: object
    properties:
      modlog:
        type:
          - integer
          - string
          - "null"
        minimum: 100000000000000000
      serverlog:
        type:
          - integer
          - string
          - "null"
        minimum: 100000000000000000
      userlog:
        type:
          - integer
          - string
          - "null"
        minimum: 100000000000000000
  staff:
    type: object
    properties:
      adminrole:
        type:
          - integer
          - string
          - "null"
        minimum: 100000000000000000
      modrole:
        type:
          - integer
          - string
          - "null"
        minimum: 100000000000000000
      botrole:
        type:
          - integer
          - string
          - "null"
        minimum: 100000000000000000
      staffchannel:
        type:
          - integer
          - string
          - "null"
        minimum: 100000000000000000
      rulesurl:
        type:
          - string
          - "null"
      appealurl:
        type:
          - string
          - "null"
  toss:
    type: object
    properties:
      tossrole:
        type:
          - integer
          - string
          - "null"
        minimum: 100000000000000000
      tosscategory:
        type:
          - integer
          - string
          - "null"
        minimum: 100000000000000000
      notificationchannel:
        type:
          - integer
          - string
          - "null"
        minimum: 100000000000000000
      tosschannels:
        type: 
          - array
          - "null"
        items:
          type:
            - integer
            - string
          minimum: 100000000000000000
      tosstopic:
        type: 
          - string
          - "null"
      tossmsg:
        type:
          - string
          - "null"
      tossmsg_rejoin:
        type:
          - string
          - "null"
      tossmsg_noreply:
        type:
          - string
          - "null"
      tossmsg_noreply_blocked:
        type:
          - string
          - "null"
  rulepush:
    type: object
    properties:
      rulepushrole:
        type: 
          - integer
          - string
          - "null"
        minimum: 100000000000000000
      rulepushcategory:
        type: 
          - integer
          - string
          - "null"
        minimum: 100000000000000000
      notificationchannel:
        type: 
          - integer
          - string
          - "null"
        minimum: 100000000000000000
      rulepushtopic:
        type:
          - string
          - "null"
      rulepushchannels:
        type: 
          - array
          - "null"
        items:
          type: 
            - integer
            - string
          minimum: 100000000000000000
      rulepushtopic:
        type: 
          - string
          - "null"
      rulepushmsg:
        type: string
      codeword_ok:
        type: string
      codeword_ko:
        type: string
      codewords_done:
        type: string
      codewords_done_timeout_secs:
        type: integer
      codewords_not_done:
        type: string
      codewords_min:
        type: integer
      codewords_max:
        type: integer
      codewords:
        type: array
        items:
          type: string
  reaction:
    type: object
    properties:
      autoreadableenable:
        type:
          - boolean
          - "null"
      noreply_threshold:
        type:
          - integer
          - "null"
      noreply_remind_every:
        type:
          - integer
          - "null"
  tenure:
    type: object
    properties:
      threshold:
        type:
          - integer
          - "null"
      role:
        type:
          - integer
          - string
          - "null"
        minimum: 100000000000000000
      role_disabled:
        type:
          - integer
          - string
          - "null"
        minimum: 100000000000000000
  overrides:
    type:
      - array
      - "null"
    items:
      type: object
      properties:
        command:
          type: string
        roles:
          type: array
          items:
            type:
              - integer
              - string
            minimum: 100000000000000000
        restrict:
          type: boolean
  drive:
    type: object
    properties:
      folder:
        type: 
          - string
          - "null"
  metadata:
    type: object
    properties:
      version:
        const: 18
